config/routes.rb
DepotTutorial::Application.routes.draw do
  
  get 'admin' => 'admin#index'

  controller :sessions do
    get  'login' => :new
    post 'login' => :create
    delete 'logout' => :destroy
  end

  scope '(:locale)' do
    resources :users
    resources :orders
    resources :line_items
    resources :carts
    resources :products do
      get :who_bought, :on => :member
    end
    root :to => 'store#index', :as => 'store'
  end

end

app/views/layouts/application.html.haml
!!! 5
%html
%head
  %title Pragprog Books Online Store
  = stylesheet_link_tag "scaffold"
  = stylesheet_link_tag "depot", :media => "all"
  = javascript_include_tag :defaults
  = csrf_meta_tag

%body#store
  #banner
    = form_tag store_path, :class => 'locale' do
      = select_tag 'set_locale', options_for_select(LANGUAGES, I18n.locale.to_s), :onchange => 'this.form.submit()'
      = submit_tag 'submit'
      = javascript_tag "$$('.locale input').each(Element.hide)"
    = image_tag("logo.png")
    = @page_title || t('.title')
  #columns
    #side
      #cart
        - if @cart
          = hidden_div_if(@cart.line_items.empty?, :id => "cart") do
            = render @cart
      %a{ :href => "http://www...." }= t('.home')
      %br
      %a{ :href => "http://www..../faq" }= t('.questions')
      %br
      %a{ :href => "http://www..../news" }= t('.news')
      %br
      %a{ :href => "http://www..../contact" }= t('.contact')
      %br
      
      - if session[:user_id]
        %br
        = link_to 'Orders', orders_path
        %br
        = link_to 'Products', products_path
        %br
        = link_to 'Users', users_path
        %br
        %br
        = button_to 'Logout', logout_path, :method => :delete      
    #main
      = yield
  
  = debug(params) if Rails.env.development?